---
- name: File module
  hosts: all

  tasks:
  - name: Create file on remote server
    file:
      path: /tmp/new_file.txt
      state: touch
      mode: ugo=r
      owner: centos02
     
  - name: Create folder
    file:
      path: /tmp/ansible_folder
      state: directory
      mode: u=rwx,g=rw,o=r
      owner: centos02 
