---
- name: Set user password
  hosts: all

  tasks:
  - name: Set pass
    user:
      name: priyanshu3006
      update_password: always
      password: "{{'@priyanshu3006' | password_hash('sha512')}}"
